[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,muldefs"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-Wl,-z,muldefs"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,muldefs"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,muldefs"]
